config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "signin", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
    get "signout", to: "devise/sessions#destroy"
  end

  root "staticpages#home"
  get "staticpages/help"
  get "staticpages/contact"
  get "staticpages/about"

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
    @user = User.new
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentalHouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/user_dashboard" %>
  <%= render "shared/header" %>
  <div class="container">
    <%= yield %>
    <%= render "shared/footer" %>
  </div>
</body>
<%= render "shared/signin_modal" %>
<%= render "shared/signup_modal" %>
</html>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar_primary">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help",   '#' %></li>
        <% if user_signed_in? %>
          <li>
            <button class="dropdown-toggle" type="button" data-toggle="dropdown">
              <%= image_tag "avatar_default.png" %> Le Dinh Minh
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
              <li role="presentation"><%= link_to "My Profile", "#" %></li>
              <li role="presentation"><%= link_to "Settings", "#" %></li>
              <li role="presentation"><%= link_to "Log out", signout_path %></li>
              <li role="presentation" class="divider"></li>
              <li><%= link_to "About Us", "#" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", "#", {data: {toggle: "modal", target: "#signin_modal"}} %></li>
          <li><%= link_to "Registration", "#", {data: {toggle: "modal", target: "#signup_modal"}} %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_signin_modal.html.erb
<div id="signin_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Login Form</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-6">
            <div class="well">
              <%= form_for( @user, url: session_path(@user)) do |f| %>
                <form id="loginForm" method="POST" action="/login/" novalidate="novalidate">
                  <div class="form-group">
                    <%= f.label :email, class: "control-label" %>
                    <%= f.email_field :email, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= f.label :password, class: "control-label" %>
                    <%= f.password_field :password, class: "form-control" %>
                  </div>
                  <div id="loginErrorMsg" class="alert alert-error hide">Wrong email og password</div>
                  <div class="checkbox">
                    <label>
                      <%= f.check_box :remember_me %> Remember login
                    </label>
                  </div>
                  <%= f.submit "Log in", class: "btn btn-success btn-block btn-signin" %>
                </form>
              <% end %>
            </div>
          </div>
          <div class="col-xs-6 another_login">
            <p class="lead">Another <span class="text-success">LOGIN</span></p>
            <ul class="list-unstyled" style="line-height: 2">
              <li>
                <a class="btn btn-block btn-social btn-twitter">
                <i class="fa fa-twitter"></i> Sign in with Twitter
                </a>
              </li>
              <li>
                <a class="btn btn-block btn-social btn-facebook">
                <i class="fa fa-facebook"></i> Sign in with Facebook
                </a>
              </li>
              <li>
                <a class="btn btn-block btn-social btn-google-plus">
                <i class="fa fa-google-plus"></i> Sign in with Google
                </a>
              </li>
              <li>
                <a class="btn btn-block btn-social btn-linkedin">
                <i class="fa fa-linkedin"></i> Sign in with Linkedin
                </a>
              </li>
            </ul>
            <p><a href="#" data-toggle="modal" data-target="#signup_modal"
                class="btn btn-info btn-block" onclick="switch_to_signup()">Yes please, register now!</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_signup_modal.html.erb
<div id="signup_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for @user, remote: true do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Registration</h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="" id="signup_form">
              <%= f.text_field :name, placeholder: "Your Name", class: "form-control input-sm" %>
              <%= f.email_field :email, placeholder: "Your Email", class: "form-control input-sm" %>
              <%= f.password_field :password, placeholder: "Password", class: "form-control input-sm" %>
              <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", class: "form-control input-sm" %>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <%= f.submit "Create my account", {class: "btn btn-info btn-block", onclick: "check_signup(#{@user.errors.full_messages.count})"} %>
          <p>OR</p>
          <a class="btn btn-success btn-block" href="#" data-toggle="modal"
            data-target="#signin_modal" onclick="switch_to_signin()">Do you want login?</a>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_user_dashboard.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuarios <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <li><a href="{{URL::to('createusuario')}}">Crear</a></li>
            <li><a href="#">Modificar</a></li>
            <li><a href="#">Reportar</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">Informes</a></li>
          </ul>
        </li>
        <li ><a href="#">Libros<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span></a></li>
        <li ><a href="#">Tags<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-tags"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/staticpages/about.html.erb
<h1>Staticpages#about</h1>
<p>Find me in app/views/staticpages/about.html.erb</p>

app/views/staticpages/contact.html.erb
<h1>Staticpages#contact</h1>
<p>Find me in app/views/staticpages/contact.html.erb</p>

app/views/staticpages/help.html.erb
<h1>Staticpages#help</h1>
<p>Find me in app/views/staticpages/help.html.erb</p>